version: '2'
services:
  itaimui-app:
    image: itaimui
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://itaimui-mysql:3306/itaimui?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://itaimui-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://itaimui-elasticsearch:9200
    ports:
      - 8081:8081
  itaimui-mysql:
    extends:
      file: mysql.yml
      service: itaimui-mysql
  itaimui-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: itaimui-elasticsearch
